#! /bin/sh

set -e

exec 3>&1
exec 1>&2

# parse payload
payload=$(mktemp)
cat > "$payload" <&0

webhook_url=$(jq -r '.source.url' < "$payload")
http_method=$(jq -r '.params.http_method // "GET"' < "$payload")
body=$(jq -r '.params.body // ""' < "$payload")

# clear temp file
rm "$payload"

curl -s -X "${http_method}" --data-urlencode "${body}" "${webhook_url}"

echo '{"version":{"ref":"none"}}' >&3
